# Generated by Django 4.1.2 on 2022-10-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='document',
            field=models.JSONField(default={}),
        ),
    ]
