# Generated by Django 4.1.2 on 2022-10-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categorie_contributor_image_metadata_tag_and_more'),
        ('books', '0004_alter_recipie_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='core.image'),
        ),
    ]
