# Generated by Django 4.1.2 on 2022-10-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_recipie_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
