# Generated by Django 4.1.2 on 2022-10-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_recipie_category_recipie_tags_alter_recipie_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RecipieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_time_minutes', models.IntegerField(default=0)),
                ('cook_time_minutes', models.IntegerField(default=0)),
                ('services', models.IntegerField(default=0)),
                ('leftover_safe', models.BooleanField(default=False)),
            ],
        ),
    ]
